{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d24b79cc-91ea-46cc-b095-837f98dfebad",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: streamlit in c:\\users\\jaski\\anaconda3\\lib\\site-packages (1.51.0)\n",
      "Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from streamlit) (5.5.0)\n",
      "Requirement already satisfied: blinker<2,>=1.5.0 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from streamlit) (1.9.0)\n",
      "Requirement already satisfied: cachetools<7,>=4.0 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from streamlit) (5.5.1)\n",
      "Requirement already satisfied: click<9,>=7.0 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from streamlit) (8.2.1)\n",
      "Requirement already satisfied: numpy<3,>=1.23 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from streamlit) (2.3.5)\n",
      "Requirement already satisfied: packaging<26,>=20 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from streamlit) (25.0)\n",
      "Requirement already satisfied: pandas<3,>=1.4.0 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from streamlit) (2.3.3)\n",
      "Requirement already satisfied: pillow<13,>=7.1.0 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from streamlit) (12.0.0)\n",
      "Requirement already satisfied: protobuf<7,>=3.20 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from streamlit) (5.29.3)\n",
      "Requirement already satisfied: pyarrow<22,>=7.0 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from streamlit) (21.0.0)\n",
      "Requirement already satisfied: requests<3,>=2.27 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from streamlit) (2.32.5)\n",
      "Requirement already satisfied: tenacity<10,>=8.1.0 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from streamlit) (9.1.2)\n",
      "Requirement already satisfied: toml<2,>=0.10.1 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from streamlit) (0.10.2)\n",
      "Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from streamlit) (4.15.0)\n",
      "Requirement already satisfied: watchdog<7,>=2.1.5 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from streamlit) (4.0.2)\n",
      "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from streamlit) (3.1.45)\n",
      "Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from streamlit) (6.5.1)\n",
      "Requirement already satisfied: jinja2 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)\n",
      "Requirement already satisfied: jsonschema>=3.0 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.0)\n",
      "Requirement already satisfied: narwhals>=1.14.2 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.7.0)\n",
      "Requirement already satisfied: colorama in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from click<9,>=7.0->streamlit) (0.4.6)\n",
      "Requirement already satisfied: gitdb<5,>=4.0.1 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)\n",
      "Requirement already satisfied: smmap<6,>=3.0.1 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.0)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
      "Requirement already satisfied: charset_normalizer<4,>=2 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (3.11)\n",
      "Requirement already satisfied: urllib3<3,>=1.21.1 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from requests<3,>=2.27->streamlit) (2026.5.20)\n",
      "Requirement already satisfied: attrs>=22.2.0 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)\n",
      "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)\n",
      "Requirement already satisfied: referencing>=0.28.4 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)\n",
      "Requirement already satisfied: rpds-py>=0.7.1 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.28.0)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in c:\\users\\jaski\\anaconda3\\lib\\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.2)\n"
     ]
    }
   ],
   "source": [
    "!pip install streamlit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "673981f1-4200-4345-ad91-20ccf50951fa",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Overwriting birthday_gift.py\n"
     ]
    }
   ],
   "source": [
    "%%writefile birthday_gift.py\n",
    "import streamlit as st\n",
    "\n",
    "# Page configuration\n",
    "st.set_page_config(page_title=\"Happy Birthday! ❤️\", page_icon=\"🎂\", layout=\"centered\")\n",
    "\n",
    "# Cute Yellow Stripes Background & Pink Buttons CSS\n",
    "st.markdown(\"\"\"\n",
    "    <style>\n",
    "    .stApp {\n",
    "        background: repeating-linear-gradient(\n",
    "          90deg,\n",
    "          #FFFDF0,\n",
    "          #FFFDF0 20px,\n",
    "          #FFF3CD 20px,\n",
    "          #FFF3CD 40px\n",
    "        );\n",
    "    }\n",
    "    div.stButton > button:first-child {\n",
    "        background-color: #FFB3B3;\n",
    "        color: white;\n",
    "        border-radius: 20px;\n",
    "        border: 2px solid #FFA0A0;\n",
    "        padding: 10px 24px;\n",
    "        font-weight: bold;\n",
    "    }\n",
    "    h1, h2, h3, h4, p, span, div {\n",
    "        color: #4A154B !important;\n",
    "        font-weight: bold !important;\n",
    "    }\n",
    "    </style>\n",
    "    \"\"\", unsafe_allow_html=True)\n",
    "\n",
    "# State management for pages\n",
    "if 'page' not in st.session_state:\n",
    "    st.session_state.page = 'login'\n",
    "\n",
    "# --- PAGE 1: ACTUAL PASSWORD LOGIN ---\n",
    "if st.session_state.page == 'login':\n",
    "    st.write(\"### Verification Required 🔒\")\n",
    "    password = st.text_input(\"Enter the password to view:\", type=\"password\")\n",
    "    captcha = st.checkbox(\"I am not a robot 🤖\")\n",
    "    \n",
    "    if st.button(\"Continue\"):\n",
    "        if password == \"Tillu Bhai\" and captcha:\n",
    "            st.session_state.page = 'challenge'\n",
    "            st.rerun()\n",
    "        elif not captcha:\n",
    "            st.warning(\"Please check the captcha first!\")\n",
    "        else:\n",
    "            st.error(\"Incorrect Password! Hint: It's the name which I love to call you 😉\")\n",
    "\n",
    "# --- PAGE 2: THE YES/NO CHALLENGE ---\n",
    "elif st.session_state.page == 'challenge':\n",
    "    st.write(\"### Hey! I made something for you, do you wanna see it? 🐶\")\n",
    "    st.image(r\"C:\\Users\\jaski\\Downloads\\WhatsApp Image 2026-08-04 at 23.52.00.jpeg\")\n",
    "    \n",
    "    col1, col2 = st.columns(2)\n",
    "    with col1:\n",
    "        if st.button(\"Yes 😍\"):\n",
    "            st.session_state.page = 'dashboard'\n",
    "            st.rerun()\n",
    "    with col2:\n",
    "        if st.button(\"No 😜\"):\n",
    "            st.session_state.page = 'sad_page'\n",
    "            st.rerun()\n",
    "\n",
    "# --- PAGE 3: FUNNY SAD PAGE ---\n",
    "elif st.session_state.page == 'sad_page':\n",
    "    st.write(\"### SERIOUSLY!? How dare you... hmph! 😡\")\n",
    "    st.image(r\"C:\\Users\\jaski\\Downloads\\WhatsApp Image 2026-08-04 at 23.52.01.jpeg\")\n",
    "    if st.button(\"Go Back ↩️\"):\n",
    "        st.session_state.page = 'challenge'\n",
    "        st.rerun()\n",
    "\n",
    "# --- PAGE 4: MAIN DASHBOARD ---\n",
    "elif st.session_state.page == 'dashboard':\n",
    "    st.write(\"## ✨ Click on each item to open ✨\")\n",
    "    col1, col2, col3 = st.columns(3)\n",
    "    \n",
    "    with col1:\n",
    "        st.write(\"📷 *Memories*\")\n",
    "        if st.button(\"Open Camera\"):\n",
    "            st.session_state.page = 'memories'\n",
    "            st.rerun()\n",
    "            \n",
    "    with col2:\n",
    "        st.write(\"✉️ *Letter*\")\n",
    "        if st.button(\"Read Message\"):\n",
    "            st.session_state.page = 'letter'\n",
    "            st.rerun()\n",
    "            \n",
    "    with col3:\n",
    "        st.write(\"🎵 *Our Song*\")\n",
    "        st.link_button(\"Play Music\", \"https://youtu.be/W1PaMD9GmCc?si=E0FwOl-TDOu7O3wm\")\n",
    "\n",
    "# --- PAGE 5: MEMORIES PHOTO GALLERY ---\n",
    "elif st.session_state.page == 'memories':\n",
    "    st.write(\"### Moments of us ❤️\")\n",
    "    st.image([\n",
    "    r\"C:\\Users\\jaski\\OneDrive\\Pictures\\tt.jpeg\",\n",
    "    r\"C:\\Users\\jaski\\OneDrive\\Pictures\\WhatsApp Image 2026-10-04 at 23.18.54.jpeg\"\n",
    "], caption=[\"Best Memories\", \"Best Bhaiii\"], width=250)\n",
    "    if st.button(\"Back to Dashboard\"):\n",
    "        st.session_state.page = 'dashboard'\n",
    "        st.rerun()\n",
    "\n",
    "# --- PAGE 6: BIRTHDAY LETTER ---\n",
    "elif st.session_state.page == 'letter':\n",
    "    st.write(\"### Happy Birthday, Tillu Bhaii! 📝\")\n",
    "    st.info(\"Tiilu Bhaii dekho!! yha mujhse bda sa paragraph to nhi likha jayega vo emoji vgera lga kr but jo likhungi smjh aa jayega utna kafi hai mere liye to tu na bohot strong hai bss apne aap pr trust rkh and Self love kr ...\")\n",
    "    if st.button(\"Back to Dashboard\"):\n",
    "        st.session_state.page = 'dashboard'\n",
    "        st.rerun()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1d65a2fa-178e-404a-bfa4-a0e219fab4fc",
   "metadata": {},
   "outputs": [],
   "source": [
    "!streamlit run birthday_gift.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "498b6b8e-1713-4b13-8e29-0d18be52782a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
